version: 2

updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
    labels:
      - "dependencies"
      - "github-actions"

  # R dependencies (for bibcheck.R)  
  - package-ecosystem: "r"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps): "
    labels:
      - "dependencies" 
      - "r"