language: generic
dist: bionic
before_install:
- .travis/travis_maybe_skip.sh
- sudo apt-get update
- sudo apt install -y -qq bibtex2html
install:
  - .travis/texlive/texlive_install.sh

cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"

script:
  - cd test && ./travis_test.sh && cd .. && ./scripts/optbib2html.sh

deploy:
  - provider: script
    script:
      - .travis/travis_deploy.sh
    skip_cleanup: true
  - provider: pages
    skip_cleanup: true
    name: $GIT_NAME
    email: $GIT_EMAIL
    github_token: $GH_TOKEN
    keep_history: true
    local_dir: web
    verbose: true
    on:
      branch: master
env:
  global:
  - GH_REPO="github.com/iridia-ulb/references.git"
  - GIT_NAME="iridiaservice"
  - GIT_EMAIL="social@iridia.ulb.ac.be"
  - secure: cAV+qxoTqBUxGhJyXA+txgn+LB5scznXXWDbc3D+l36lp9YMbC5yFgRwMiFdNK2d0k+tvKfCS19hWP1UmqpZYMt7Z68x/sMOJiJauS7Ag9sj48YgYNAu+aZudtDPlQ18Yrixb15VeF25w1xMaYGe2Jt63WVXh/Ikz54RCXmhBvjWGyDleUnIVwWLPfEqMB4StbbWk+YbBwoKM4eCJuYpusk39SqLW70VCbVLrXq4cjB3YhEfqNH64BRd5NLjEcAVPAc3fn+0594q32PVegdYPDeSD58FnmotFQeU2CZxHxP/WEiRE/jTrMXH8pQE35/uVFBlaNHWN05FLzM2lwygQIY7/hOeAKPE/t1Rf2sHWEwwNJzBsYOITrVDKen/eF7LlpqwLwIYpNejfqXfLdD49KaVYanZD9plkaxd5n/bE0nwyTw3TqtW7aBx4/jYBOIt+WLVzkFmSWwLpn5XZPNUhiENdTo3924ueJwo+SRwyL2KH86M7lub/E8aUgfRhqo9CZ6Dk0C/exPLcX2aWgOrDJuUBi0g/TaHqTzdz9pMxI3Q8wacfrvw7T+knFFT6o5svobOD7nhRcpw06fu74giiUwXgMEWJabm0+tAbzlk+bDhxlTWh4RwI8rSz7xbU0vViAPiZqV/tY3TxD1gb7g7OTr63fbLWzjlQmTzI9j1LQE=
