#!/bin/bash
set -u
set -o pipefail
# TODO:
# * Whitelist of invalid urls to not check
# * Check DOI

check_url() {
    if curl -L --head --silent --no-styled-output --fail $1 &> /dev/null; then
        return 0
    else
        echo "$1 does not exist."
        return 1
    fi
}

for filename in "$@"; do
    if [[ $filename == *.bib ]]; then
        grep -v '^%' "$filename" | grep --no-filename -o '[{"]https\?://[^"}]\+[}"]' | while read -r line ; do
            # Remove first and last characters
            url=${line:1:-1}
            if ! check_url $url; then
                grep -H -n $url "$filename"
            fi
        done
    fi
done


