#!/usr/bin/env bash
# If any command fails, exit immediately with that command's exit status
set -eo pipefail

TYPES="string Article Misc InCollection InProceedings InBook Book TechReport PhDThesis MastersThesis Unpublished Manual COMMENT PREAMBLE"

CHANGED=0
tmpfile="$(mktemp)"
for filename in "$@"; do
    case "$filename" in
        *".bib")
            cat --squeeze-blank $filename > $tmpfile
            # Remove trailing whitespace.
            sed -i 's/[[:space:]]\+$//' $tmpfile
            for pattern in $TYPES; do
                sed -i "s/^\s*@${pattern}/@${pattern}/gi" $tmpfile
            done
            # Lowercase field names.
            sed -i -E 's/^(\s*[a-zA-Z]+\s*=)/\L\1/g' $tmpfile

            if ! diff -q "$filename" "$tmpfile" &> /dev/null; then
                CHANGED=1
                cp $tmpfile $filename
            fi
            if [[ $filename == *authors.bib ]]; then
                (head -n 150 $tmpfile | grep '^%'; grep ^@ $tmpfile | env LC_COLLATE=C sort -u --ignore-case; tail -n 150 $tmpfile | grep '^%')> $filename
            fi
            if ! diff -q "$filename" "$tmpfile" &> /dev/null; then
                CHANGED=1
            fi
            ;;
    esac
done
rm -f "$tmpfile"
exit $CHANGED
