#!/usr/bin/env bash
# If any command fails, exit immediately with that command's exit status
set -eo pipefail

TYPES="string Article Misc InCollection InProceedings InBook Book Proceedings TechReport PhDThesis MastersThesis Unpublished Manual COMMENT PREAMBLE"

CHANGED=0
tmpfile="$(mktemp)"
for filename in "$@"; do
    case "$filename" in
        *".bib")
            cat --squeeze-blank $filename > $tmpfile
            # Remove trailing whitespace.
            sed -i 's/[[:space:]]\+$//' $tmpfile
            # Canonical entry types
            for pattern in $TYPES; do
                sed -i "s/^\s*@${pattern}\s*/@${pattern}/gi" $tmpfile
            done
            # Lowercase field names.
            sed -i -E 's/^(\s*[a-zA-Z]+\s*=)/\L\1/g' $tmpfile
            # "# and #" -> #and#
            sed -i -E 's/#\s*and\s*#/#and#/g' $tmpfile
            # '# " and others "' -> '# and_others
            sed -i -E 's/#\s*["{]\s*and others\s*["}]/# and_others/g' $tmpfile
            sed -i -E 's/#\s*and\s*#\s*["{]\s*others\s*["}]/# and_others/g' $tmpfile
            sed -i -E 's/#\s*and_others/# and_others/g' $tmpfile
            # Remove langid = {english}. This should be the default langid.
            sed -i -E 's/^\s*(langid|language)\s*=\s*["{]en(glish)?["}].*$//gi' $tmpfile

            # Fix field names:
            sed -i -E 's/^(\s*)anote\s*=/\1annote =/g' $tmpfile
            sed -i -E 's/^(\s*)keyword\s*=/\1keywords =/g' $tmpfile
            
            # Remove extra newlines.
            sed -z -i 's/[}]\n\n\n\+/}\n\n/g' $tmpfile
            sed -z -i 's/,\n\n\+/,\n/g' $tmpfile
            sed -z -i 's/\n\n\+[}]/\n}/g' $tmpfile
            
            if ! diff -q "$filename" "$tmpfile" &> /dev/null; then
                CHANGED=1
                cp $tmpfile $filename
            fi
            # Sort authors.bib and journals.bib
            if [[ $filename == *authors.bib || $filename == *journals.bib ]]; then
                (head -n 150 $tmpfile | grep '^%'; grep ^@ $tmpfile | env LC_COLLATE=C sort -u --ignore-case; tail -n 150 $tmpfile | grep '^%')> $filename
                if ! diff -q "$filename" "$tmpfile" &> /dev/null; then
                    CHANGED=1
                fi
            fi
            ;;
    esac
done
rm -f "$tmpfile"
exit $CHANGED
