#!/usr/bin/env bash
# If any command fails, exit immediately with that command's exit status
set -eo pipefail

# Find all changed files for this commit
# Compute the diff only once to save a small amount of time.
CHANGED_FILES=$(git diff --name-only --cached --diff-filter=ACMR)
# Get only changed files that match our file suffix pattern
get_pattern_files() {
    pattern=$(echo "$*" | sed "s/ /\$\\\|/g")
    echo "$CHANGED_FILES" | { grep "$pattern$" || true; }
}
# Get all changed bib files
BIB_FILES=$(get_pattern_files .bib)

if [[ -n "$BIB_FILES" ]]; then
    ./test/fast_check.sh $BIB_FILES
    echo "Pre-commit check passed!"
fi
