#!/usr/bin/env bash
# If any command fails, exit immediately with that command's exit status
set -eo pipefail

# Find all changed files for this commit
# Compute the diff only once to save a small amount of time.
CHANGED_FILES=$(git diff --name-only --cached --diff-filter=ACMR)
# Get only changed files that match our file suffix pattern
get_pattern_files() {
    pattern=$(echo "$*" | sed "s/ /\$\\\|/g")
    echo "$CHANGED_FILES" | { grep "$pattern$" || true; }
}
# Get all changed bib files
BIB_FILES=$(get_pattern_files .bib)
failed() {
    echo -e '\033[41mFAILED\033[0m!'
    echo "$1"
    exit 1
}

if [[ -n "$BIB_FILES" ]]; then
    echo -n "Pre-commit check ........ "
    if ERROR=$(./scripts/fast_check.sh $BIB_FILES); then
        echo "passed!"
    else
        failed "$ERROR"
    fi
    echo -n "Linter .................. "
    if ! ./scripts/linter $BIB_FILES; then
        failed "The linter made some changes. Revise them and try again."
    fi
    echo "passed!"
    case "$BIB_FILES" in
        *"crossref.bib"*|*"biblio.bib"*)
            echo -n "bibcheck.R .............. "
            if ! Rscript ./scripts/bibcheck.R; then
                failed
            fi
            echo "passed!"
    esac
fi
