#!/usr/bin/env bash
# If any command fails, exit immediately with that command's exit status
set -eo pipefail

# Find all changed files for this commit
# Compute the diff only once to save a small amount of time.
CHANGED_FILES=$(git diff --name-only --cached --diff-filter=ACMR)
# Get only changed files that match our file suffix pattern
get_pattern_files() {
    pattern=$(echo "$*" | sed "s/ /\$\\\|/g")
    echo "$CHANGED_FILES" | { grep "$pattern$" || true; }
}
# Get all changed bib files
BIB_FILES=$(get_pattern_files .bib)

if [[ -n "$BIB_FILES" ]]; then
    echo -n "Pre-commit check ........ "
    if ! ./test/fast_check.sh $BIB_FILES; then
        echo "FAILED!"
        exit 1
    fi
    echo "passed!"
    echo -n "bibcheck.R .............. "
    if ! Rscript ./scripts/bibcheck.R; then
        echo "FAILED!"
        exit 1
    fi
    echo "passed!"
    echo -n "Linter .................. "
    if ! ./scripts/linter $BIB_FILES; then
        echo "FAILED! The linter made some changes. Revise them and try again."
        exit 1
    fi
    echo "passed!"
fi
