name: GitHub Actions Demo

on: ['push', 'pull_request']

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Maybe skip before install (.travis/travis_maybe_skip.sh)
        run: |
          set -u
          INCLUDE_ONLY="\.bib\|\.tex\|travis\|optbib2html\|deploy"
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/* 
          if [ "${GITHUB_EVENT_NAME}" = "pull_request" ]; then 
             echo "This is a pull request build" 
             base_sha=$(git show --pretty=raw | grep '^parent' | cut -f2 -d' ' | sed -n '1p') 
             head_sha=$(git show --pretty=raw | grep '^parent' | cut -f2 -d' ' | sed -n '2p') 
             export TRAVIS_COMMIT_RANGE=${base_sha}...${head_sha} 
          else 
             echo "This is a branch build" 
             git fetch --depth=50 origin ${{ github.ref }} 
             export TRAVIS_COMMIT_RANGE=$(git log --format="%H" | tail -n1)...${{ github.ref }} 
          fi 
          echo "Emulated TRAVIS_COMMIT_RANGE: ${TRAVIS_COMMIT_RANGE}" 
          git log --oneline --graph ${TRAVIS_COMMIT_RANGE} 
          # Use -m so that merge commits are also considered
          echo git diff --raw -c --no-commit-id --name-only ${TRAVIS_COMMIT_RANGE}
          git diff --raw -c --no-commit-id --name-only ${TRAVIS_COMMIT_RANGE} | grep -e ${INCLUDE_ONLY} --quiet
          if [ $? -ne 0 ]; then
            exit 1
          fi
          set +u
                  
      - name: Install packages
        run: sudo apt -y install bibtex2html tidy

      - name: Install texlive
        run: .travis/texlive/texlive_install.sh

      - name: Run test
        run: cd test && ./travis_test.sh && cd .. && ./scripts/optbib2html.sh
        
      - run: echo "🍏 This job's status is ${{ job.status }}."
