name: GitHub Actions Demo

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-20.04
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}

      - name: Maybe skip before install
        run: .travis/travis_maybe_skip.sh
        
      - name: Install packages
        run: sudo apt -y install bibtex2html tidy

      - name: Install texlive
        run: .travis/texlive/texlive_install.sh

      - name: Run test
        run: cd test && ./travis_test.sh && cd .. && ./scripts/optbib2html.sh
        
      - run: echo "🍏 This job's status is ${{ job.status }}."
