name: PR Check

on:
  pull_request:
    paths-ignore: ['README.md','bibpool/**','**precommit','setup_worktree.sh','mklog','**.latexmkrc','.gitignore', '.github/**']

permissions:
  contents: read
  pull-requests: write

env:
  cache-version: v2

jobs:
  check:
    name: Pull Request Validation
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🔍 Analyze changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            bibfiles: ['**.bib']
            scripts: ['scripts/**']
            tests: ['test/**']

      - name: ⚡ Quick validation
        if: steps.changes.outputs.bibfiles == 'true'
        run: |
          echo "🔍 Running quick BibTeX validation..."
          ./test/fast_check.sh *.bib

      - name: 🧹 Check formatting
        if: steps.changes.outputs.bibfiles == 'true'
        run: |
          echo "🧹 Checking if files are properly formatted..."
          cp *.bib /tmp/
          ./scripts/linter *.bib

          # Check if linter made any changes
          CHANGED_FILES=""
          for file in *.bib; do
            if ! diff -q "$file" "/tmp/$file" > /dev/null 2>&1; then
              CHANGED_FILES="$CHANGED_FILES $file"
            fi
          done

          if [ -n "$CHANGED_FILES" ]; then
            echo "❌ The following files need formatting:$CHANGED_FILES"
            echo "Please run './scripts/linter *.bib' and commit the changes."
            exit 1
          else
            echo "✅ All files are properly formatted!"
          fi

      - name: 📊 Comment on PR
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.issue.number;
            const comment = `## ❌ Pull Request Check Failed

            The automated checks found issues with your pull request:

            - **Formatting**: Some BibTeX files need to be reformatted
            - **Fix**: Run \`./scripts/linter *.bib\` locally and commit the changes

            Please address these issues and push the fixes to update this pull request.

            <details>
            <summary>View workflow details</summary>

            **Workflow:** ${{ github.workflow }}
            **Run ID:** ${{ github.run_id }}

            </details>`;

            github.rest.issues.createComment({
              issue_number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
